modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Jasons-impart/Constructs-Armory-Report/issues"
logoFile="${mod_icon}"
license="LGPL-3.0-or-later"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.constructsarmoryreport]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.constructsarmoryreport]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.constructsarmoryreport]]
    modId="tconstruct"
    mandatory=true
    versionRange="[1.19.2-3.8.0.14,)"
    ordering="NONE"
    side="BOTH"
